2021-06-18 04:11:03,541 INFO    MainThread:4059481 [internal.py:wandb_internal():91] W&B internal server running at pid: 4059481, started at: 2021-06-18 04:11:03.541291
2021-06-18 04:11:03,551 INFO    WriterThread:4059481 [datastore.py:open_for_write():80] open: /home/chengzilong/DDQN/wandb/offline-run-20210618_041101-120my781/run-120my781.wandb
2021-06-18 04:11:03,553 DEBUG   HandlerThread:4059481 [handler.py:handle_request():124] handle_request: run_start
2021-06-18 04:11:05,797 DEBUG   HandlerThread:4059481 [meta.py:__init__():39] meta init
2021-06-18 04:11:05,797 DEBUG   HandlerThread:4059481 [meta.py:__init__():53] meta init done
2021-06-18 04:11:05,798 DEBUG   HandlerThread:4059481 [meta.py:probe():210] probe
2021-06-18 04:11:05,804 DEBUG   HandlerThread:4059481 [git.py:repo():33] git repository is invalid
2021-06-18 04:11:05,804 DEBUG   HandlerThread:4059481 [meta.py:_save_pip():57] save pip
2021-06-18 04:11:05,806 DEBUG   HandlerThread:4059481 [meta.py:_save_pip():71] save pip done
2021-06-18 04:11:05,807 DEBUG   HandlerThread:4059481 [meta.py:_save_conda():78] save conda
2021-06-18 04:11:10,256 DEBUG   HandlerThread:4059481 [meta.py:_save_conda():86] save conda done
2021-06-18 04:11:10,256 DEBUG   HandlerThread:4059481 [meta.py:probe():252] probe done
