2021-06-16 01:35:08,077 INFO    MainThread:581913 [internal.py:wandb_internal():91] W&B internal server running at pid: 581913, started at: 2021-06-16 01:35:08.077368
2021-06-16 01:35:08,080 DEBUG   HandlerThread:581913 [handler.py:handle_request():124] handle_request: check_version
2021-06-16 01:35:08,080 INFO    WriterThread:581913 [datastore.py:open_for_write():80] open: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/run-2xyfwkrz.wandb
2021-06-16 01:35:08,084 DEBUG   SenderThread:581913 [sender.py:send():179] send: header
2021-06-16 01:35:08,084 DEBUG   SenderThread:581913 [sender.py:send_request():193] send_request: check_version
2021-06-16 01:35:08,130 DEBUG   SenderThread:581913 [sender.py:send():179] send: run
2021-06-16 01:35:08,138 DEBUG   SenderThread:581913 [git.py:repo():33] git repository is invalid
2021-06-16 01:35:08,397 INFO    SenderThread:581913 [dir_watcher.py:__init__():168] watching files in: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files
2021-06-16 01:35:08,397 INFO    SenderThread:581913 [sender.py:_start_run_threads():707] run started: 2xyfwkrz with start time 1623778507
2021-06-16 01:35:08,397 DEBUG   SenderThread:581913 [sender.py:send():179] send: summary
2021-06-16 01:35:08,398 INFO    SenderThread:581913 [sender.py:_save_file():829] saving file wandb-summary.json with policy end
2021-06-16 01:35:08,400 DEBUG   HandlerThread:581913 [handler.py:handle_request():124] handle_request: run_start
2021-06-16 01:35:08,640 WARNING MainThread:581913 [internal.py:wandb_internal():147] Internal process interrupt: 1
2021-06-16 01:35:08,812 WARNING MainThread:581913 [internal.py:wandb_internal():147] Internal process interrupt: 2
2021-06-16 01:35:08,812 ERROR   MainThread:581913 [internal.py:wandb_internal():150] Internal process interrupted.
2021-06-16 01:35:09,130 INFO    WriterThread:581913 [datastore.py:close():288] close: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/run-2xyfwkrz.wandb
2021-06-16 01:35:09,472 INFO    SenderThread:581913 [sender.py:finish():933] shutting down sender
2021-06-16 01:35:09,473 INFO    SenderThread:581913 [dir_watcher.py:finish():282] shutting down directory watcher
2021-06-16 01:35:09,475 INFO    Thread-8  :581913 [dir_watcher.py:_on_file_created():216] file/dir created: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files/wandb-summary.json
2021-06-16 01:35:09,479 INFO    SenderThread:581913 [dir_watcher.py:finish():312] scan: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files
2021-06-16 01:35:09,481 INFO    SenderThread:581913 [dir_watcher.py:finish():318] scan save: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files/config.yaml config.yaml
2021-06-16 01:35:09,482 INFO    SenderThread:581913 [dir_watcher.py:finish():318] scan save: /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files/wandb-summary.json wandb-summary.json
2021-06-16 01:35:09,483 INFO    SenderThread:581913 [file_pusher.py:finish():176] shutting down file pusher
2021-06-16 01:35:09,483 INFO    SenderThread:581913 [file_pusher.py:join():181] waiting for file pusher
2021-06-16 01:35:09,687 DEBUG   HandlerThread:581913 [meta.py:__init__():39] meta init
2021-06-16 01:35:09,687 DEBUG   HandlerThread:581913 [meta.py:__init__():53] meta init done
2021-06-16 01:35:09,687 DEBUG   HandlerThread:581913 [meta.py:probe():210] probe
2021-06-16 01:35:09,694 DEBUG   HandlerThread:581913 [git.py:repo():33] git repository is invalid
2021-06-16 01:35:09,694 DEBUG   HandlerThread:581913 [meta.py:_save_pip():57] save pip
2021-06-16 01:35:09,694 DEBUG   HandlerThread:581913 [meta.py:_save_pip():71] save pip done
2021-06-16 01:35:09,694 DEBUG   HandlerThread:581913 [meta.py:_save_conda():78] save conda
2021-06-16 01:35:10,850 INFO    Thread-11 :581913 [upload_job.py:push():133] Uploaded file /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files/wandb-summary.json
2021-06-16 01:35:11,925 INFO    Thread-10 :581913 [upload_job.py:push():133] Uploaded file /home/chengzilong/DDQN/wandb/run-20210616_013507-2xyfwkrz/files/config.yaml
2021-06-16 01:35:14,145 DEBUG   HandlerThread:581913 [meta.py:_save_conda():86] save conda done
2021-06-16 01:35:14,146 DEBUG   HandlerThread:581913 [meta.py:probe():252] probe done
2021-06-16 01:35:14,150 INFO    HandlerThread:581913 [handler.py:finish():638] shutting down handler
2021-06-16 01:35:14,151 INFO    MainThread:581913 [internal.py:handle_exit():78] Internal process exited
