2021-06-18 03:57:02,176 INFO    MainThread:4020099 [internal.py:wandb_internal():91] W&B internal server running at pid: 4020099, started at: 2021-06-18 03:57:02.176467
2021-06-18 03:57:02,187 DEBUG   HandlerThread:4020099 [handler.py:handle_request():124] handle_request: run_start
2021-06-18 03:57:02,192 INFO    WriterThread:4020099 [datastore.py:open_for_write():80] open: /home/chengzilong/DDQN/wandb/offline-run-20210618_035700-19azw9nj/run-19azw9nj.wandb
2021-06-18 03:57:04,466 DEBUG   HandlerThread:4020099 [meta.py:__init__():39] meta init
2021-06-18 03:57:04,467 DEBUG   HandlerThread:4020099 [meta.py:__init__():53] meta init done
2021-06-18 03:57:04,467 DEBUG   HandlerThread:4020099 [meta.py:probe():210] probe
2021-06-18 03:57:04,473 DEBUG   HandlerThread:4020099 [git.py:repo():33] git repository is invalid
2021-06-18 03:57:04,473 DEBUG   HandlerThread:4020099 [meta.py:_save_pip():57] save pip
2021-06-18 03:57:04,475 DEBUG   HandlerThread:4020099 [meta.py:_save_pip():71] save pip done
2021-06-18 03:57:04,476 DEBUG   HandlerThread:4020099 [meta.py:_save_conda():78] save conda
2021-06-18 03:57:08,964 DEBUG   HandlerThread:4020099 [meta.py:_save_conda():86] save conda done
2021-06-18 03:57:08,965 DEBUG   HandlerThread:4020099 [meta.py:probe():252] probe done
