Process ActorAsync-3:
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/chengzilong/DDQN/ActorAsync.py", line 30, in run
    op, data = self.__worker_pipe.recv()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/connection.py", line 251, in recv
    return _ForkingPickler.loads(buf.getbuffer())
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/multiprocessing/reductions.py", line 108, in rebuild_cuda_tensor
    torch.cuda._lazy_init()
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/site-packages/torch/cuda/__init__.py", line 161, in _lazy_init
    "Cannot re-initialize CUDA in forked subprocess. To use CUDA with "
