Process ReplayBufferAsync-2:
Traceback (most recent call last):
  File "/home/chengzilong/anaconda3/envs/myenv/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/chengzilong/DDQN/ReplayBufferAsync2.py", line 86, in run
    print(self.out_pointer, self.in_pointer, self.current_cache_size)
